<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<IsTestProject>true</IsTestProject>
	<RootNamespace>Alisflyt.IntegrationTests</RootNamespace>
	<AssemblyName>Alisflyt.IntegrationTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../Alisflyt.Infrastructure/Alisflyt.Infrastructure.csproj" />
  </ItemGroup>

</Project>
