<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<IsTestProject>true</IsTestProject>
	<RootNamespace>Alisflyt.Application.Tests</RootNamespace>
	<AssemblyName>Alisflyt.Application.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../Alisflyt.Application/Alisflyt.Application.csproj" />
	<ProjectReference Include="../../Alisflyt.Domain/Alisflyt.Domain.csproj" />
  </ItemGroup>

</Project>
