<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>Alisflyt.Application</RootNamespace>
	<AssemblyName>Alisflyt.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../Alisflyt.Domain/Alisflyt.Domain.csproj" />
  </ItemGroup>

</Project>
